language: php
php: 7.2
env:
    - COMPOSER_NO_INTERACTION=1
install:
    - travis_retry composer install
before_script:
    - composer lint
script:
    - composer test
after_success:
    - bash <(curl -s https://codecov.io/bash)
cache:
    directories:
        - $HOME/.composer/cache
